name: 3. Create Certificates
run-name: Create Certificates (${{ github.ref_name }})
on:
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate_secrets.yml
    secrets: inherit
  
  certificates:
    name: Create Certificates
    needs: validate
    runs-on: macos-14
    steps:
      # Uncomment to manually select Xcode version if needed
      - name: Select Xcode version
        run: "sudo xcode-select --switch /Applications/Xcode_15.0.1.app/Contents/Developer"
      
      # Checks-out the repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Install project dependencies
      - name: Install Project Dependencies
        run: bundle install
        
      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: sed -i "" "/puts(Terminal::Table.new(params))/d" $(dirname $(gem which match))/match/table_printer.rb || exit 2

      # Sync the GitHub runner clock with the Windows time server (workaround as suggested in https://github.com/actions/runner/issues/2996)
      - name: Sync clock
        run: sudo sntp -sS time.windows.com

      # Create or update certificates for app
      - name: Create Certificates
        run: bundle exec fastlane certs
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
